[build]
  functions = "functions"
  command = "npm run build"  # Replace with your build command if necessary

[build.environment]
  MONGODB_URI = "mongodb+srv://dyamez:VRLDCepNOSJJCmBy@cluster0.jog0s17.mongodb.net/farmfriends"
